apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-tb07297
  region: ap-northeast-2
  version: "1.35"
  tags: {tool: eksctl}

kubernetesNetworkConfig:
  ipFamily: IPv4
  serviceIPv4CIDR: "10.128.0.0/16"

vpc:
  id: "vpc-03841f019c1ecc756"
  subnets:
    public:
      ap-northeast-2a: { id: subnet-0ba67de4e64599e8d }
      ap-northeast-2b: { id: subnet-0f88fa66e41a53600 }
    private:
      ap-northeast-2a: { id: subnet-03cea3f8ba88173ea }
      ap-northeast-2b: { id: subnet-0a99c143eca28ec73 }
  controlPlaneSecurityGroupIDs: [ "sg-0871b732e2357246e" ]
  clusterEndpoints:
    privateAccess: true
    publicAccess: false
  publicAccessCIDRs: [ 218.237.76.216/32 ]

iam:
  serviceRoleARN: "arn:aws:iam::xxxxxxxxxxxx:role/tb07297-eks-cluster-role"
  withOIDC: true

managedNodeGroups:
  - name: management
    labels: { role: management }
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    subnets: [ subnet-03cea3f8ba88173ea, subnet-0a99c143eca28ec73 ]
    volumeSize: 80
    privateNetworking: true
    tags: {finops-start: skip, finops-stop: skip}
    iam:
      instanceRoleARN: "arn:aws:iam::xxxxxxxxxxxx:role/tb07297-eks-nodegroup-role"
    securityGroups:
      attachIDs: [ sg-0871b732e2357246e ]
    volumeType: gp3
  - name: worker
    labels: { role: workers }
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    subnets: [ subnet-03cea3f8ba88173ea, subnet-0a99c143eca28ec73 ]
    volumeSize: 80
    privateNetworking: true
    tags: {finops-start: skip, finops-stop: skip}
    iam:
      instanceRoleARN: "arn:aws:iam::xxxxxxxxxxxx:role/tb07297-eks-nodegroup-role"
    securityGroups:
      attachIDs: [ sg-0871b732e2357246e ]
    volumeType: gp3

# Managed Addons 설정
addons:
  - name: vpc-cni        # 기본 필수 애드온
  - name: kube-proxy     # 기본 필수 애드온
  - name: coredns        # 기본 필수 애드온
  - name: metrics-server # [추가] Metrics Server 활성화
    version: latest      # 특정 버전을 지정하거나 최신 버전 사용