########################################################################
###
###   eksctl config reference site: https://schema.eksctl.io/
###
########################################################################

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-tb07297
  region: ap-northeast-2

managedNodeGroups:
  - name: worker
    instanceType: t3.medium
    subnets:
      - subnet-03cea3f8ba88173ea
      - subnet-0a99c143eca28ec73    # Private의 1개 subnet에만 배포점검서 주석처리
    desiredCapacity: 2   # autoscaler config  - coredns 는 replica: 2 참고하기. 정상 배포되려면 2개 이상 배포
    minSize: 1           # autoscaler config
    maxSize: 3           # autoscaler config
    volumeSize: 100           # 파일용량 100 GiB
    ssh:
      allow: true
      publicKeyName: key-mgmt-eks-node   # AWS에 등록될 key pair 명칭
    labels:
      role: worker
    privateNetworking: true   # Private Subnet으로 배포
    tags:
      finops-start: skip
      finops-stop: skip    # EKS Cluster NodeGroup Tag 설정하기
    iam:
      instanceRoleARN: "arn:aws:iam::xxxxxxxxxxxx:role/tb07297-eks-nodegroup-role"  # EKS Cluster Node Group Role
    securityGroups:
      attachIDs:
        - sg-0871b732e2357246e  # node에서 application 관리용Security Group
    volumeType: gp3
    disableIMDSv1: true       # IMDSv2 강제 적용
    #taints:
    #  - key: dedicated
    #    value: infrastructure
    #    effect: NoSchedule
