########################################################################
###
###   eksctl config reference site: https://schema.eksctl.io/
###
########################################################################

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster-<project_name>-<environment>
  region: ap-northeast-2

managedNodeGroups:
  - name: management
    instanceType: t3.medium
    subnets:
<mgmt_node_subnets>
    desiredCapacity: 2   # autoscaler config  - coredns 는 replica: 2 참고하기. 정상 배포되려면 2개 이상 배포
    minSize: 1           # autoscaler config
    maxSize: 3           # autoscaler config
    volumeSize: 100           # 파일용량 100 GiB
    ssh:
      allow: true
      publicKeyName: key-mgmt-eks-node   # AWS에 등록될 key pair 명칭
    labels:
<mgmt_node_labels>
    privateNetworking: true   # Private Subnet으로 배포
    tags:
<mgmt_node_tags>
    iam:
      instanceRoleARN: "arn:aws:iam::<account_id>:role/role-<project_name>-<environment>-eks-nodegroup-role"  # EKS Cluster Node Group Role
    securityGroups:
      attachIDs:
<mgmt_node_sg_ids>
                    # node에서 application 관리용Security Group
    volumeType: gp3
    disableIMDSv1: true       # IMDSv2 강제 적용
    taints:
<mgmt_node_taints>
  - name: worker
    instanceType: t3.medium
    subnets:
<worker_node_subnets>
    desiredCapacity: 2   # autoscaler config  - coredns 는 replica: 2 참고하기. 정상 배포되려면 2개 이상 배포
    minSize: 1           # autoscaler config
    maxSize: 3           # autoscaler config
    volumeSize: 100           # 파일용량 100 GiB
    ssh:
      allow: true
      publicKeyName: key-mgmt-eks-node   # AWS에 등록될 key pair 명칭
    labels:
<worker_node_labels>
    privateNetworking: true   # Private Subnet으로 배포
    tags:
<worker_node_tags>
    iam:
      instanceRoleARN: "arn:aws:iam::<account_id>:role/role-<project_name>-<environment>-eks-nodegroup-role"  # EKS Cluster Node Group Role
    securityGroups:
      attachIDs:
<worker_node_sg_ids>
                       # node에서 application 관리용Security Group
    volumeType: gp3
    disableIMDSv1: true       # IMDSv2 강제 적용
    taints:
<worker_node_taints>
